[tool.poetry]
name = "mode-client"
version = "0.0.5"
description = "A typed Python client for the Mode Analytics APIs"
authors = ["Kshitij Aranke <kshitij@aranke.org>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.9"
httpx = "^0.22.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
