name: Test

on: [push]

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Run mypy
      run: poetry run mypy mode_client

  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
      max-parallel: 1
    env:
      MODE_WORKSPACE: mode_client
      MODE_TOKEN: ${{ secrets.MODE_TOKEN }}
      MODE_PASSWORD: ${{ secrets.MODE_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: pipx install poetry
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install
    - name: Run pytest
      run: poetry run pytest --cov=mode_client tests/ --cov-report=xml
    - name: Upload coverage report
      if: ${{ matrix.python-version }} == '3.9'
      uses: codecov/codecov-action@v3
